### PR TITLE
Fixed WAILA/HWYLA support

### LINKED ISSUE #45: [1.10.2] Hwyla support?
Can you add support for Hwyla on 1.10.2?
https://github.com/TehNut/HWYLA

image

### LINKED ISSUE #71: [1.10.2] Walia/HWYLA Support
@TheRoBrit Hello! First of, thank you for your work on this. It is a great mod!

However, it does not work properly with Walia, HWYLA, or the One Probe to display fluid type. I would like to know why ThexXTURBOXx 's file mentioned in [Issue #45](https://github.com/TheRoBrit/Moo-Fluids/issues/45) works beautifully with Hwyla for 1.10.2, and your official release still does not. I understand not supporting his build of the mod, but you could at least take a look at it, to try and figure out what he did right.

You have stated in numerous issue posts about this that you were working on it, or that it was fixed, but it has been over a year now at least and it is still not working. And yet, for more than half that time, a working file has sat completely ignored by you.

I don't know, just seems silly to completely disregard a potential fix just because someone else came up with it.

### PR DESCRIPTION
**Pull request by ThexXTURBOXx**
and even fixed support for other mods with this mod as dependency
Closes #45 
Closes #71 

Download here: http://femtopedia.de/MooFluids-1.10.2-1.7.02.12b.jar

And even some sources and deobfuscated things, if you want:
http://femtopedia.de/MooFluids-1.10.2-1.7.02.12b-sources.jar
http://femtopedia.de/MooFluids-1.10.2-1.7.02.12b-deobf.jar

### CODE REVIEW

**Comment by RoBrit** [comment]
Hi @ThexXTURBOXx, 

Firstly, apologies for the late response but I've previously had this project on hiatus. I've created an 'experimental' branch for changes suggest by yourself and others, to that end if you would be able to create a new pull-request directed to the 'experimental' branch instead of the '1.12.2' branch, that would be appreciated. 

Thank you.

**Comment by ThexXTURBOXx** [comment]
Ok, I can see... I will do this. No problem for the late response though ^^

**Comment by ThexXTURBOXx** [comment]
One slight problem: This PR is for 1.10.2... Why should I push this in the 1.12.2-experimental-branch then?

**Comment by RoBrit** [comment]
Ah, you are indeed correct. This is for 1.10.2. For now I will close this issue, investigate further on whether the changes are still needed (depending on user usage) and re-open if required. Current focus is getting the project back going for current MC versions. Thank you for your work however, I do appreciate the time and effort taken.

**Pull request closed without merging**
