### PR TITLE
Only reset cooldown when some interaction succeeds. Fixes #72

### LINKED ISSUE #72: Fluid cows reset timer even without bucket
Interacting with a ready fluid cow will reset the timer regardless of whether the player is holding a bucket, any other item or even nothing.

MooFluids-1.12.2-1.7.11.02a

### PR DESCRIPTION
**Pull request by Tora-B**
Currently, the cooldown resets whenever the player interacts with the cow and the cooldown is up, even if they're not holding anything. I've rearranged processInteract() to only reset the cooldown if one of the tasks succeeds. Fixes #72.

### CODE REVIEW

**Comment by RoBrit** [comment]
Hi @Tora-B, 

Firstly, apologies for the late response but I've previously had this project on hiatus. I've created an 'experimental' branch for changes suggest by yourself and others, to that end if you would be able to create a new pull-request directed to the 'experimental' branch instead of the '1.12.2' branch, that would be appreciated. 

Thank you.

**Comment by Tora-B** [comment]
I've just retargeted my existing pull requests to the experimental branch. Is that acceptable, or would you prefer that I create new pull requests?

**Comment by RoBrit** [comment]
Retargeting for the 'experimental' branch is perfectly fine. Thanks. I'll take a look as to ordering of these PRs and get back to you.

**Comment by Tora-B** [comment]
These changes are included in #77, so I'll just close this one to reduce the conflicts when merging.

**Pull request closed without merging**
